make:
	make proj5.x

proj5.x: passserver.h passserver.cpp hashtable.h hashtable.hpp proj5.cpp
	g++ -std=c++11 -lcrypt -o proj5.x proj5.cpp passserver.cpp

s: passserver.h passserver.cpp hashtable.h hashtable.hpp sproj5.cpp
	g++ -std=c++11 -lcrypt -o sproj5.x sproj5.cpp passserver.cpp
clean:
	rm proj5.x sproj5.x
	
